"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class control_command_t(object):

    __slots__ = ["timestamp", "xyzrpy"]

    __typenames__ = ["int64_t", "double"]

    __dimensions__ = [None, [6]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.xyzrpy = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """

    def encode(self):
        buf = BytesIO()
        buf.write(control_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>6d', *self.xyzrpy[:6]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = control_command_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.xyzrpy = struct.unpack('>6d', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if control_command_t in parents: return 0
        tmphash = (0x7861f1f8eae0c3e8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if control_command_t._packed_fingerprint is None:
            control_command_t._packed_fingerprint = struct.pack(">Q", control_command_t._get_hash_recursive([]))
        return control_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", control_command_t._get_packed_fingerprint())[0]

