"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class franka_state_t(object):

    __slots__ = ["timestamp_ns", "q", "q_d", "K_F_ext_hat_K", "O_F_ext_hat_K", "O_T_EE", "O_T_EE_d"]

    __typenames__ = ["int64_t", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, [7], [7], [6], [6], [16], [16]]

    def __init__(self):
        self.timestamp_ns = 0
        """ LCM Type: int64_t """
        self.q = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """
        self.q_d = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """
        self.K_F_ext_hat_K = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.O_F_ext_hat_K = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.O_T_EE = [ 0.0 for dim0 in range(16) ]
        """ LCM Type: double[16] """
        self.O_T_EE_d = [ 0.0 for dim0 in range(16) ]
        """ LCM Type: double[16] """

    def encode(self):
        buf = BytesIO()
        buf.write(franka_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp_ns))
        buf.write(struct.pack('>7d', *self.q[:7]))
        buf.write(struct.pack('>7d', *self.q_d[:7]))
        buf.write(struct.pack('>6d', *self.K_F_ext_hat_K[:6]))
        buf.write(struct.pack('>6d', *self.O_F_ext_hat_K[:6]))
        buf.write(struct.pack('>16d', *self.O_T_EE[:16]))
        buf.write(struct.pack('>16d', *self.O_T_EE_d[:16]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != franka_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return franka_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = franka_state_t()
        self.timestamp_ns = struct.unpack(">q", buf.read(8))[0]
        self.q = struct.unpack('>7d', buf.read(56))
        self.q_d = struct.unpack('>7d', buf.read(56))
        self.K_F_ext_hat_K = struct.unpack('>6d', buf.read(48))
        self.O_F_ext_hat_K = struct.unpack('>6d', buf.read(48))
        self.O_T_EE = struct.unpack('>16d', buf.read(128))
        self.O_T_EE_d = struct.unpack('>16d', buf.read(128))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if franka_state_t in parents: return 0
        tmphash = (0xb374cca6d896e955) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if franka_state_t._packed_fingerprint is None:
            franka_state_t._packed_fingerprint = struct.pack(">Q", franka_state_t._get_hash_recursive([]))
        return franka_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", franka_state_t._get_packed_fingerprint())[0]

